### ISSUE TITLE
【バグ】 `Exit`でタスクを削除できていない

### ISSUE THREAD

**Issue by a-happin** [a-happin/rail_update_visualizer#2]

**Comment by a-happin** [comment]
https://github.com/a-happin/update_visualizer/issues/1#issuecomment-1101942769

**Comment by a-happin** [comment]
Errorが出ている状態で、
```mcfunction
data get storage update_visualizer: 
```
の結果がみたいです

**Comment by a-happin** [comment]
私の環境では再現しない…

**Comment by a-happin** [comment]
`Exit`をクリックした時点でfalling_blockを`/kill`するはずなのにそれが動いてないのが気になる…

**Comment by a-happin** [comment]
```mcfunction
datapack list
```
の結果も見たいです

**Comment by enokilovin** [comment]
画像１枚目：`datapack list`
![2022-04-19_17 50 24](https://user-images.githubusercontent.com/61267241/163966554-5e193df6-325e-410c-9f5b-0a1ef9607640.png)
  
  

画像２枚目：`data get storage update_visualizer:` [Visualize → Next Step 時：Next Step 不発 & Error]
![2022-04-19_17 51 40](https://user-images.githubusercontent.com/61267241/163967816-a7d9eed8-8663-4658-8682-7649dbbd4643.png)
  
  

画像３枚目：`data get storage update_visualizer:` [Next Step → Exit 時：Exit 不発 & Next Step 発動]
![2022-04-19_17 57 46](https://user-images.githubusercontent.com/61267241/163968798-f49f11b9-d21b-4156-a564-834655b8fa5a.png)
  
  

...という感じです ;3

追記：バニラ環境だと自分も正常な動作を得られたので何かしらのModが干渉しているかもしれません。調べてみます
追々記：ワールドを変えたら正常に動きました！（Mod干渉関係なし）変なコマンドを打ってしまったのでしょうか…

**Comment by enokilovin** [comment]
バグ報告したときのワールド（1.18.2）をバニラ環境で遊んでみたら例のバグを再現できましたので一応↓
[InstaRailPrincipia.zip](https://github.com/a-happin/update_visualizer/files/8511879/InstaRailPrincipia.zip)

ひとまず、別のワールドで一通り遊んでみてもバグは確認できませんでした。

**Comment by a-happin** [comment]
`datapack list`の結果がおかしいですね…

データパックを読み込む順番が
`01.player_event`→`02.player_event.used.id`→`update_visualizer`の順番じゃないと正しく動作しません。(そういう仕様です)

アップデート手順を間違えたかそもそも私の提案したアップデート手順がおかしかった可能性があります。

ひとまずの対処法としては、
```mcfunction
datapack disable "file/update_visualizer-master"
datapack enable "file/update_visualizer-master" last
```
で治ると思います

**Comment by a-happin** [comment]
この状態だとVisualizeも動かなさそうだけどなんで動いてるんだろう🤔

**Comment by a-happin** [comment]
Modは多分関係ないですね

**Comment by enokilovin** [comment]
なるほど読み込む順番が関係しているんですね…
お騒がせしました(._.)

**Comment by a-happin** [comment]
> この状態だとVisualizeも動かなさそうだけどなんで動いてるんだろう🤔

`player_event.used_id`で手に持ったアイテムのidを取得して、
`update_visualizer`でそれを利用しているので
順番が逆転すると1つずれるのか、なるほど

**Comment by a-happin** [comment]
正直私がREADMEにインストール手順を書いてないのが悪い
